# Generated by Django 6.0.1 on 2026-01-17 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bestset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='mesocycle',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='bestset',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='mesocycle',
            unique_together=set(),
        ),
    ]
