# Generated by Django 6.0.1 on 2026-01-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_exercise_userprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestset',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
