# Generated by Django 6.0.1 on 2026-01-14 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_bestset_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bestset',
            name='date',
        ),
    ]
