# Generated by Django 6.0.1 on 2026-01-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_bestset_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='primary_goal',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='training_experience',
        ),
    ]
