# Generated by Django 6.0.1 on 2026-01-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_exercise_options_remove_exercise_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesocycle',
            name='rir',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mesocycle',
            name='rpe',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mesocycle',
            name='target_weight',
            field=models.FloatField(),
        ),
    ]
