# Generated by Django 6.0.1 on 2026-01-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_mesocycle_rir_alter_mesocycle_rpe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestset',
            name='estimated_1rm',
            field=models.FloatField(help_text='Calculated 1RM (Brzycki)'),
        ),
        migrations.AlterField(
            model_name='bestset',
            name='reps',
            field=models.IntegerField(help_text='Repetitions'),
        ),
        migrations.AlterField(
            model_name='bestset',
            name='weight',
            field=models.FloatField(help_text='Weight in kg'),
        ),
    ]
